### ISSUE TITLE
Make_CMWP_instrumental.py has an error  in line141 'np.sum(pars) '

### ISSUE THREAD

**Issue by YpXiaQQ** [rhysgt/cmwp_tools#2]
Variable ‘pars’ is a list of Parameter.   np.sum(pars) will return an error. 
Do you have any idea ?

**Comment by rhysgt** [comment]
In my version, this does not return an error. Can you post more details of the full error message please and I will try to resolve.

**Comment by YpXiaQQ** [comment]
Thanks for your kind reply. I've revised the code and it works now.

**Comment by rhysgt** [comment]
Could you please let me know what you changed? This would be useful in case others come up with the same problem.

I have made a slightly improved version of the script here also: Make_CMWP_instrumental-Lab-Copy1.ipynb

Does the script work well for you? Are there any other changes you have made to improve the process?
